server.port=8085
spring.application.name=ai-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.ai.google.genai.api-key=${key}
spring.ai.google.genai.chat.options.model=gemini-1.5-pro
spring.ai.google.genai.chat.options.temperature=0.7

management.endpoints.web.exposure.include=health,info,metrics
